---
name: Build Image (without publishing)
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Image
      uses: docker/build-push-action@v5
      with:
        push: false
        platforms: |
          linux/amd64
          linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
