---
name: Main Tests
on:
  push:
    branches: [main]
jobs:
  server-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"
    - name: Install libgstreamer1.0-dev
      run: |
        sudo apt-get install -y libunwind-dev
        sudo apt-get install -y --no-install-recommends libgstreamer1.0-dev
    - name: Run Tests
      run: go test -v -count 2 -race ./...
  client-build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install Packages
      run: cd client && yarn install --frozen-lockfile
    - name: Build Client
      run: cd client && yarn build
    - name: Check for Prettier Style
      run: cd client && yarn prettier --check src
    - name: Check for ESLint Violations
      run: cd client && yarn eslint .
