---
name: Publish Image
on:
  workflow_run:
    workflows: [Basic Tests]
    types: [completed]
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/ahamlinman/hypcast:latest
        platforms: |
          linux/amd64
          linux/arm64
          linux/arm/v7
        cache-from: type=gha
        cache-to: type=gha
